### ISSUE TITLE
Runtime build error

### ISSUE THREAD

**Issue by Logikgate** [NativeScript/ns-v8ios-runtime#112]
Hello!

I am attempting to build the runtime in order to debug the issues outlined [here](https://github.com/nstudio/nativescript-plugins/issues/12) for nativescript-camera-plus but am running into an issue when running the TestRunner (see below screenshot).  I'm unsure where to go from here, any help/hints would be appreciated!

<img width="821" alt="Screen Shot 2021-04-09 at 5 20 11 PM" src="https://user-images.githubusercontent.com/2379994/114241860-e817a400-9957-11eb-8485-587f3cf8b1f7.png">

**Comment by darind** [comment]
Make sure you have cloned the llvm git submodule of this repository.

**Comment by Logikgate** [comment]
That was it, thank you! 

Mind if I open a pull request to add `git submodule update --init` to the Getting Started section of the README?

**Comment by rigor789** [comment]
@Logikgate go for it! 💯
