### ISSUE TITLE
Webview not visualised correctly 

### ISSUE THREAD

**Issue by vhristov5555** [NativeScript/ns-v8ios-runtime#13]
1. Git clone `https://github.com/NativeScript/NativeScript.git`
2. Navigate to `NativeScript/e2e/ui-tests-app`
3. `rm -rf node_modules`
4. `rm -rf platforms`
5. `rm -rf package-lock.json`
6. Open package.json and edit this fields to next version:
    - ` "tns-platform-declarations": "next"`
    - `"tns-core-modules": "next"`
    - `"@nativescript/core": "next"`
7. Add new iosV8 ` tns platform add ios@alpha-v8 `
8. Run the app `tns run ios`
9. In the application click `webview`
10 . Click `query` or `webtest`
Actual:
The HTML queries or webtest are not visualised correctly. For example:
**this is in the standart ios version**
![image](https://user-images.githubusercontent.com/7846198/69343693-bf194500-0c76-11ea-91fd-37b401d3a0ce.png)
**this is in the iosV8**
![image](https://user-images.githubusercontent.com/7846198/69343719-cb9d9d80-0c76-11ea-8c35-3be1877c0d95.png)
**Also all queries are not visualised correctly for example**
**standart ios**
![image](https://user-images.githubusercontent.com/7846198/69343904-246d3600-0c77-11ea-9bfe-64c93f8e0447.png)
**iosV8**
![image](https://user-images.githubusercontent.com/7846198/69343924-2e8f3480-0c77-11ea-98f9-dcab9eb5d353.png)

**Comment by darind** [comment]
Closing the issue for inactivity. Please re-open if the issue persists or manifests under some other form.
