### ISSUE TITLE
DYSM for 8.1.0

### ISSUE THREAD

**Issue by tobydeh** [NativeScript/ns-v8ios-runtime#130]
Where can I download the dysm assets for 8.1.0?

**Comment by rigor789** [comment]
They should be packaged inside the `XCFramework`:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/879060/140921868-a641a223-5ebb-44db-8ad8-cd72844ccf46.png">

**Comment by tobydeh** [comment]
Great, thank you! Do I need to do anything to receive symbolicated crash reports from apple?

**Comment by rigor789** [comment]
I don't think so, if you open the crash report along the project (`platforms/<projectName>.xcworkspace`) - I believe it should automatically symbolicate.

**Comment by tobydeh** [comment]
Awesome, thanks.
