### ISSUE TITLE
Data Corruption caused by NS 8.1 PR #127

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/ns-v8ios-runtime#131]
@rigor789 @darind - There appears to be a corner case bug if the string passed in is "" (empty). Only occurs with NS 8.1 runtime, and we tracked it down to empty string being passed in. I figured out a work around in my case, but the issue is definitely something in the 8.1 runtime as 8.0 works great. My guess is the #127 here is causing the issue as it probably is NOT creating a null terminated 0 length string properly (i.e. the string I believe should technically be 1 character, a single null character).

**Comment by darind** [comment]
@NathanaelA, can you please provide a sample illustrating the issue?

**Comment by NathanaelA** [comment]
See the thread here: https://github.com/NathanaelA/nativescript-sqlite/issues/173

The If you clone my demo app in the repo and then type in "test" as the name, it will run all the tests.  However use the prior NS-Sqlite version (as the latest version works around the NS 8.1 issue). 

The issue is when you send a empty string as a parameter when it is converted to its "c" string -- it is no longer a zero terminated string (since for a zero terminated string you actually have to have one character for the null character).  So whatever Sqlite gets it then treats it as a blob (as it is still a valid memory pointer, just no zero termination character)  and writes the wrong "data" to the record causing the string field to then become a blob field..

**Comment by darind** [comment]
@NathanaelA, #132 should address this issue.

**Comment by NathanaelA** [comment]
@darind - Looked at the PR but didn't trace things down into the classes, can you confirm that the last character in the string will now be a `\0` (null) character?    Or will it be filled with whatever was in memory when allocated?     Most memory allocators do NOT zero fill allocated memory -- so you tend to have to manually `\0` (null) the last character...    But you know the code better to be able to confirm if something elsewhere puts a null character as the last char or you are using a zero-filling allocator.

**Comment by darind** [comment]
@NathanaelA, this PR adjusts the string length passed to v8’s ExternalString accounting for the null terminating character. So for example, the length of the empty string should be 1 instead of 0.

**Comment by NathanaelA** [comment]
Yes, I saw that, off the top of my head I believe that should fix it.   :+1:       But was wanting to verify that when it marshals the data from JS to a C string in this new class that was added in 8.1, that it actually does get the \0 null character appended to it as that might also need to be accounted for.

**Comment by NathanWalker** [comment]
Thanks @darind, https://github.com/NativeScript/ns-v8ios-runtime/pull/132 published in `8.2.0-alpha.0` - Upon confirmation this issue can be closed and will be included with 8.2 in coming weeks.
