### ISSUE TITLE
Getting a syntax error for for ios code NS6

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/ns-v8ios-runtime#162]
Getting a syntax error on the following ios specific code in Nativescript 6.x

`
navigationBar.standardAppearance.titleTextAttributes =
   NSDictionary.dictionaryWithDictionary({
        [NSForegroundColorAttributeName]: UIColor.whiteColor
      });
`

Message

`
Argument of type '{ [x: string]: UIColor; }' is not assignable to parameter of type 'NSDictionary<unknown, unknown>'.
  Type '{ [x: string]: UIColor; }' is missing the following properties from type 'NSDictionary<unknown, unknown>': allKeys, allValues, count, descriptionInStringsFileFormat, 
`

How can this be fixed.

**Comment by rigor789** [comment]
If you can't update your `tns-platform-declarations` to use latest `@nativescript/types` instead - you can just do `// @ts-ignore` above the line.

This is just a TypeScript error, and it should work fine during runtime.
