### ISSUE TITLE
split is not a function

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#19]
In my app i do something like this:
```ts
const deviceLang = Platform.device.language;
const dayjsLocale = deviceLang.split('-')[0].toLowerCase();
```
Now it crashes with the error:
```
deviceLang.split is not a function
```
Logging i see that `typeof deviceLang` is `object`

**Comment by darind** [comment]
@farfromrefug, thanks for reporting this issue, we have released a fix for it.

**Comment by farfromrefug** [comment]
@darind i can confirm it is fixed
