### ISSUE TITLE
Assertion failed: (wrapper != nullptr), function WriteValue

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#20]
Navigating between pages, my app crashes with:
```
Assertion failed: (wrapper != nullptr), function WriteValue, file /Users/nsbuilduser/workspace/master-ios-v8-runtime/NativeScript/runtime/Interop.mm, line 251.
```
Cant really tell you where it happens in JS as i get no stack.
<img width="1651" alt="Screen Shot 2020-01-20 at 10 06 30" src="https://user-images.githubusercontent.com/655344/72713109-b8228c00-3b6c-11ea-957d-2ddcf3aea8a3.png">

**Comment by darind** [comment]
Could you send a sample project exhibiting this error?

**Comment by farfromrefug** [comment]
@darind right now it is with a client project. Need to see if i can reproduce with a very simple project. Will let you know

**Comment by darind** [comment]
@farfromrefug, I have released a patch which will log the native and javascript stacktraces in case of assertion failures. Could you please try it and see you can see it in the native logs?

**Comment by farfromrefug** [comment]
@darind here is the new one:
```
====== Assertion failed ======
Native stack trace:
1          0x10ab1839b tns::Assert(bool, v8::Isolate*) + 119
2          0x10ab393cc tns::Interop::WriteValue(v8::Isolate*, tns::TypeEncoding const*, void*, v8::Local<v8::Value>) + 2792
3          0x10ab388bf tns::Interop::SetFFIParams(v8::Isolate*, tns::TypeEncoding const*, tns::FFICall*, int, int, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >) + 99
4          0x10ab3827e tns::Interop::CallFunctionInternal(v8::Isolate*, bool, void*, tns::TypeEncoding const*, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >, objc_object*, objc_class*, objc_selector*, bool, tns::MetaType, bool) + 432
5          0x10ab38089 tns::Interop::CallFunction(v8::Isolate*, void*, tns::TypeEncoding const*, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >) + 87
6          0x10ab37fdd tns::Interop::CallFunction(v8::Isolate*, tns::FunctionMeta const*, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >) + 159
7          0x10aade565 tns::MetadataBuilder::CFunctionCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 119
8          0x10ac3e33c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 620
9          0x10ac3d7ec v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 556
10         0x10ac3ce63 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 259
11         0x10b4b0079 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
JavaScript stack trace:
at <anonymous> (file:///app/vendor.js:91138:9)
at <anonymous> (file:///app/vendor.js:89220:26)
at <anonymous> (file:///app/vendor.js:91964:12)
at <anonymous> (file:///app/vendor.js:92310:12)
at <anonymous> (file:///app/vendor.js:91710:20)
at <anonymous> (file:///app/vendor.js:4923:17)
at <anonymous> (file:///app/vendor.js:91709:23)
```
And looking at the code i see that it actually happens with one of my plugins [nativescript-canvas](https://github.com/Akylas/nativescript-canvas)
It happens here
https://github.com/Akylas/nativescript-canvas/blob/master/src/canvas.ios.ts#L1547
Also it happens on the simulator so i think ```FloatConstructor``` is actually ```Float64Array```

You can run the demo-vue inside the project.
* clone the project
* run `tns platform add ios@beta-v8 ` in the `demo-vue`
* run `npm run demo.ios`
* launch the shapes example and it will crash

BTW: if you keep the JS stack in the error report (which is awesome) can you "fix" it ? LIke have method name so that we can get source maps?

**Comment by darind** [comment]
@farfromrefug, thanks for the additional details. We have released a fix. Could you please try it and let us know if it resolves this particular issue?

Also we have included the function names in javascript stacktraces that are being shown during crashes in Debug builds.

**Comment by farfromrefug** [comment]
@darind the bug is fixed!
Though i stumbled upon another error. Do you prefer here or another bug request?

**Comment by darind** [comment]
Opening a new issue would be better for tracking those. Thanks!

**Comment by Thisgio** [comment]
> @darind the bug is fixed!
> Though i stumbled upon another error. Do you prefer here or another bug request?

Where is the new one?
