### ISSUE TITLE
cannot read property 'queryActivityStartingFromDateToDateToQueueWithHandler' of null

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#22]
I have an error when accessing `queryActivityStartingFromDateToDateToQueueWithHandler` on a `CMMotionActivityManager` [here](https://github.com/farfromrefug/nativescript-perms/blob/d59841e4f087f5a59bcbfc3257d3815eca0869b3/src/permissions.ios.ts#L331)
It seems the `new` is not working

**Comment by darind** [comment]
Fixed.

**Comment by farfromrefug** [comment]
@darind confirmed!
