### ISSUE TITLE
EXEC_BAD_ACCESS while dynamically adding view

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#23]
i am facing that error
<img width="1499" alt="Screen Shot 2020-01-22 at 16 22 49" src="https://user-images.githubusercontent.com/655344/72908686-223a5d00-3d36-11ea-9ec6-fb108388fd60.png">
Now this is within my app but i managed to reproduce it within one of my plugins `nativescript-material-components`
You can find it [here](https://github.com/Akylas/nativescript-material-components)
* fork
* npm `run build.plugin`
* add the v8 to the demo-vue
* run the demo
* go in the first example "buttons"
* click on the save button in the actionbar => crash(wont happen with current runtime)

**Comment by darind** [comment]
Fixed.

**Comment by farfromrefug** [comment]
@darind i can confirm it is fixed!
Thanks
