### ISSUE TITLE
Stuck on 'Linking' phase in XCode build...

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/ns-v8ios-runtime#25]
With tns-ios `6.5.0-beta.2-v8-2020-01-28-165547-02` against a large project we manage I experience XCode build getting stuck on the 'Linking' phase for infinite amount of time (45 minutes and counting on a build attempt). I don't see anything in the build log in particular that jumps out but perhaps you may know.

Here's the full build log:
https://drive.google.com/file/d/15qmE4jaJIIYyywtm4RNxWgNXeYfNTWSK/view?usp=sharing

I can provide entire project zipped up that you can try the build via Slack if you ping me. I can provide a google drive link to download.

**Comment by darind** [comment]
@NathanWalker, we have released a fix for this. Please try the latest `tns-ios@beta-v8` package and let us know if you are still experiencing any issues.

**Comment by NathanWalker** [comment]
@darind wow. just wow. Worked perfect and the speed difference is quite noticeable. I'm quite thrilled - thank you! How safe would it be to go to production using this v8 runtime? The app works 100% so far from what I've seen which is quite impressive 👏 🎉

**Comment by NathanWalker** [comment]
I did run into one interesting thing. When navigating back out of a view that was playing a video I got this:
```
====== Assertion failed ======
====== Assertion failed ======
Native stack trace:
Native stack trace:
1          0x11200d2eb tns::Assert(bool, v8::Isolate*) + 119
1          0x11200d2eb tns::Assert(bool, v8::Isolate*) + 119
2          0x111f7a4db tns::ArgConverter::MethodCallback(ffi_cif*, void*, void**, void*) + 301
2          0x111f7a4db tns::ArgConverter::MethodCallback(ffi_cif*, void*, void**, void*) + 301
3          0x1120ac166 ffi_closure_unix64_inner + 662
3          0x1120ac166 ffi_closure_unix64_inner + 662
4          0x1120ad3ea ffi_closure_unix64 + 72
4          0x1120ad3ea ffi_closure_unix64 + 72
5       0x7fff22f2d86b _CFNetworkHTTPConnectionCacheSetLimit + 205915
5       0x7fff22f2d76f _CFNetworkHTTPConnectionCacheSetLimit + 205663
6       0x7fff25732d61 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
6       0x7fff25732d61 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
7       0x7fff25732c59 -[NSBlockOperation main] + 98
7       0x7fff25732c59 -[NSBlockOperation main] + 98
8       0x7fff25735be6 __NSOPERATION_IS_INVOKING_MAIN__ + 17
8       0x7fff25735be6 __NSOPERATION_IS_INVOKING_MAIN__ + 17
9       0x7fff25731e59 -[NSOperation start] + 731
9       0x7fff25731e59 -[NSOperation start] + 731
10      0x7fff25736540 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
10      0x7fff25736540 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
11      0x7fff2573604a __NSOQSchedule_f + 182
11      0x7fff2573604a __NSOQSchedule_f + 182
12      0x7fff519eb265 _dispatch_block_async_invoke2 + 83
12      0x7fff519eb265 _dispatch_block_async_invoke2 + 83
13      0x7fff519de7b9 _dispatch_client_callout + 8
13      0x7fff519de7b9 _dispatch_client_callout + 8
14      0x7fff519e0b75 _dispatch_continuation_pop + 440
14      0x7fff519e0b75 _dispatch_continuation_pop + 440
15      0x7fff519e0241 _dispatch_async_redirect_invoke + 817
15      0x7fff519e0241 _dispatch_async_redirect_invoke + 817
16      0x7fff519edbf9 _dispatch_root_queue_drain + 350
16      0x7fff519edbf9 _dispatch_root_queue_drain + 350
17      0x7fff519ee39b _dispatch_worker_thread2 + 99
17      0x7fff519ee39b _dispatch_worker_thread2 + 99
18      0x7fff51c016b6 _pthread_wqthread + 220
18      0x7fff51c016b6 _pthread_wqthread + 220
19      0x7fff51c00827 start_wqthread + 15
19      0x7fff51c00827 start_wqthread + 15
```
Lemme know if you'd prefer me open a new issue for that one or if might have idea what that stack could be result of.

**Comment by darind** [comment]
@NathanWalker, thanks for confirming. You can leave it here. Is this crash consistent and if yes, what are the steps to reproduce it? I will have a look.

**Comment by NathanWalker** [comment]
Thanks @darind - in that same project I shared with you via Slack (added login details in slack for you to use) - tap on the 2nd tab icon at top (looks like a diamond), then choose 'Play' on the first item in the list there. Let the video play for a moment and then tap the top left navigation back icon to get the stack above 👍

**Comment by darind** [comment]
@NathanWalker, we have released a fix for this crash. When you get the chance you can try it and let us know if you are still encountering any problems.

**Comment by NathanWalker** [comment]
I'm closing this - @darind is incredible. Fixed both issues raised. v8 works great in a very large project of ours now and we are even considering trying in production.
