### ISSUE TITLE
App crash after start

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ns-v8ios-runtime#26]
Hello,

I am trying `6.5.0-beta.2-v8-2020-01-29-122856-01` version for my APP. I am getting following problem

<img width="1392" alt="Screen Shot 2020-01-29 at 6 48 59 PM" src="https://user-images.githubusercontent.com/6080277/73358212-52e73d00-42c8-11ea-9c49-19d8ff452b49.png">

```
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@ngneat/transloco": "^2.12.4",
    "@nota/nativescript-webview-ext": "^6.2.1",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "moment": "^2.24.0",
    "nativescript-angular": "^8.20.4",
    "nativescript-audio": "^5.0.5",
    "nativescript-braintree": "^2.0.7",
    "nativescript-carousel": "^6.1.1",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-clipboard": "~1.2.0",
    "nativescript-image-cache-it": "^5.0.0-alpha.3",
    "nativescript-md5": "^1.0.1",
    "nativescript-pdf-view": "^2.1.0",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-simple-libsodium": "^1.0.6",
    "nativescript-social-share": "^1.6.0",
    "nativescript-sqlite": "^2.3.3",
    "nativescript-theme-core": "1.0.6",
    "nativescript-toasty": "^2.0.1",
    "nativescript-ui-calendar": "^6.0.0",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-videoplayer": "^4.2.1",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.3.2",
    "zone.js": "^0.9.1"
```

**Comment by darind** [comment]
@jibon57, can you share some sample app illustrating the crash?

**Comment by jibon57** [comment]
@darind thanks for reply. I think it's happening for `nativescript-image-cache-it` plugin.

```
 <ImageCacheIt class="img" height="300" stretch="aspectFit"
                                                        *ngIf="item.img" row="0" src="{{item.img}}"></ImageCacheIt>
```
If I am using regular `Image` then it's working fine.

**Comment by darind** [comment]
@jibon57, thanks for the update! I will try to reproduce the crash and will share my findings once I have some information.

**Comment by darind** [comment]
@jibon57, I have tried using the `nativescript-image-cache-it` plugin in a hello world angular application and it worked fine. Maybe there's some specifics in your project that are making it fail. If you cannot share your project source code, can you try narrowing it down to a simple example illustrating the issue?

**Comment by darind** [comment]
@jibon57, I have managed to reproduce the crash and I am be working on a fix. I will let you know once we release it.

**Comment by darind** [comment]
@jibon57, we have released a fix for this crash. Could you please try re-adding the `ios` platform from the latest `beta-v8` tag and see if it resolves the issue in your application?

**Comment by jibon57** [comment]
@darind thanks a lot :) working perfectly :)
