### ISSUE TITLE
Not working with nativescript-baidu-push-notifications 

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ns-v8ios-runtime#27]
Hello,

I am having following problem with [nativescript-baidu-push-notifications](https://github.com/jibon57/nativescript-baidu-push-notifications)

<img width="1405" alt="Screen Shot 2020-02-02 at 9 48 10 PM" src="https://user-images.githubusercontent.com/6080277/73611013-bbefed00-4607-11ea-993f-9a5275a17f9f.png">

Thanks

**Comment by darind** [comment]
@jibon57, can you share a sample project exhibiting this error?

**Comment by jibon57** [comment]
Thanks for reply. Can I get your email address please? I'll send you source code of my project.

**Comment by darind** [comment]
@jibon57, you can send me the project at darin.dimitrov@progress.com

**Comment by jibon57** [comment]
@darind , thanks. I have sent you an email

**Comment by darind** [comment]
I have tried running your app with the latest available fixes and it doesn't seem to crash on the device. I also got the `SUCCESSFULLY REGISTER BAIDU PUSH NOTIFICATION` message logged after allowing the app to receive push notifications.

Could you verify if the app is still crashing and if yes, what are the exact steps?

**Comment by jibon57** [comment]
@darind thank you! Yes, from device it's working. Sorry, I was testing from simulator. But if you try with default ios runtime then you will get some error message if you are using simulator. But using this runtime it will crash the APP.

**Comment by darind** [comment]
@jibon57, I managed to reproduce the issue on the iPhone Simulator. It is related to a bug in the `console.dir` implementation with some exotic object. I am working on a fix.

**Comment by darind** [comment]
@jibon57, we have released a fix in the `console.dir` function. Could you please verify that the error message is now properly logged in the iPhone Simulator without crashing?

**Comment by jibon57** [comment]
Thanks... it's working :)
