### ISSUE TITLE
Problem with DKImagePickerController

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ns-v8ios-runtime#29]
I am trying to implement [DKImagePickerController](https://github.com/zhangao0086/DKImagePickerController) library in one of my project. I have added in my app's `Podfile` like this:
`pod 'DKImagePickerController'`
It was working until `6.5.0-beta.2-v8-2020-02-05-153040-01` but in latest version getting crash.

```
let picker = DKImagePickerController.new();
picker.assetType = DKImagePickerControllerAssetType.AllPhotos;
picker.singleSelect = true;

picker.didSelectAssets = ((res) => {
console.dir(res);
})
```

<img width="1397" alt="Screen Shot 2020-02-13 at 6 26 20 PM" src="https://user-images.githubusercontent.com/6080277/74435337-68df2b00-4e8e-11ea-8b05-fcb832642b29.png">

**Comment by darind** [comment]
@jibon57, thanks for submitting this issue. Could you please provide a sample project?

**Comment by jibon57** [comment]
@darind , thanks for reply. I have attached sample project. Please have a look

[Archive.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/4198396/Archive.zip)

**Comment by darind** [comment]
@jibon57, thanks for the sample project. We have released a fix. Could you please try it out?

**Comment by jibon57** [comment]
@jibon57 thank you! Working now
