### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#33]
With the v8 runtime and the latest {N} my app crashes with this:
```
-[UIView transform3D]: unrecognized selector sent to instance 0x7fb8f47462f0
```
I am running on an ios 12 simulator .

It is for a view i apply a translate to. Thus i think the crash happens here:
https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/core/view/view.ios.ts#L372

It is not happening with 6.4.1

**Comment by darind** [comment]
By the way did you try running this on an iOS 13 simulator (https://stackoverflow.com/questions/57133781/ios-13-uiview-transform3d)?

**Comment by farfromrefug** [comment]
@darind it works on the 13.0 simulator, crashes on the 12.0
And i am not using that prop, {N} is ;)
But why is the 6.4.1 runtime working. 
Can it be a question of metadata? like you expect transform3D to be a property, which it is not on 12.0, and the older runtime does not expect anything, so it does not crash as it sees that as just an undefined prop from JS (if you see what i mean).

**Comment by darind** [comment]
@farfromrefug, that's correct. In addition to the availability attributes, the old runtime also applies logic if the instance responds to the corresponding selector. The reason for this is because there are inconsistencies in the iOS SDK like the one you have encountered.

I will apply the same check in the new runtime as well.

**Comment by darind** [comment]
@farfromrefug, did you have the chance to check the released fix?

**Comment by farfromrefug** [comment]
@darind sorry for the late reply. I ran a quick test and it seems to work perfectly!
Thanks
