### ISSUE TITLE
Worker not return anything with MS cognitiveservices

### ISSUE THREAD

**Issue by jibon57** [NativeScript/ns-v8ios-runtime#36]
I am implementing MS cognitiveservices for NativeScript under worker. Using official runtime I am getting result after I record but using `V8` nothing.

[Archive_2.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/4299671/Archive_2.zip)

Click on "Navigate > Record" but working fine with `Play`. Have one issue with Android too: https://github.com/NativeScript/android-runtime/issues/1591

**Comment by jibon57** [comment]
I can see one error:

```
CONSOLE ERROR: ERROR Error: Uncaught (in promise): TypeError: properties.getPropertyById is not a function
TypeError: properties.getPropertyById is not a function
at MoodleGlossaryComponent.<anonymous> (file: src/app/moodle/courseMods/glossary/glossary.component.ts:688:44)
```

**Comment by darind** [comment]
I am getting the following error when I try to build your project:

```
ERROR in ./workers/mscognitiveservices.worker.ts (../node_modules/nativescript-dev-webpack/moduleid-compat-loader.js!../node_modules/nativescript-dev-webpack/lazy-ngmodule-hot-loader.js!../node_modules/@ngtools/webpack/src!./workers/mscognitiveservices.worker.ts)
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: The AngularCompilerPlugin was not found. The @ngtools/webpack loader requires the plugin.
    at Object.ngcLoader (/Users/<someuser>/nativescript/azure-cognitive-services/node_modules/@ngtools/webpack/src/loader.js:27:15)
Executing webpack failed with exit code 2.
```

**Comment by jibon57** [comment]
@darind I can compile perfectly. My environment:

✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.4.1 version and is up to date.
✔ Component tns-core-modules has 6.4.2 version and is up to date.
✔ Component tns-android has 6.4.1 version and is up to date.
✔ Component tns-ios has 6.5.0-beta.2-v8-2020-03-06-182159-01 version and is up to date.

```
[./package.json] 134 bytes {bundle} {tns_modules/tns-core-modules/inspector_modules} [optional] [built]
    + 615 hidden modules
Child worker:
                             Asset      Size  Chunks             Chunk Names
    3e3ffe36eed31c736fa5.worker.js  4.72 MiB    main  [emitted]  main
    Entrypoint main = 3e3ffe36eed31c736fa5.worker.js
    [../node_modules/ts-loader/index.js!./workers/mscognitiveservices.worker.ts] ../node_modules/ts-loader!./workers/mscognitiveservices.worker.ts 6.61 KiB {main} [built]
    [./package.json] 134 bytes {main} [optional] [built]
        + 282 hidden modules
Webpack compilation complete. Watching for file changes.

```

[Archive 2.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/4301586/Archive.2.zip)

**Comment by jibon57** [comment]
@darind I think the problem is happening for `mscognitiveservices.worker.ts` line 119. If I remove that line then I can get output. Looks like that method isn't available in runtime. If you try same project with official runtime then it will work.

**Comment by darind** [comment]
I was able to build and run the project. When I click Navigate > Record, I get the following output:

```
2020-03-07 11:14:29.756846+0200 azurecognitiveservices[75390:2358086] CONSOLE LOG: {
  "task": "record"
}
2020-03-07 11:14:29.938721+0200 azurecognitiveservices[75390:2358640]  PropertyID=1667788144 is NULL
2020-03-07 11:14:36.113866+0200 azurecognitiveservices[75390:2358086] Unknown CancellationReason value: 0.
2020-03-07 11:14:36.115071+0200 azurecognitiveservices[75390:2358086] CONSOLE LOG:
2020-03-07 11:14:36.118405+0200 azurecognitiveservices[75390:2357918] file:///app/bundle.js:262:21:
==== object dump start ====
data: "{"gotResult":false,"msg":"NoMatch"}"
==== object dump end ====
```

I think that this condition is not satisfied on line 116:

```
if (speechResult.reason == SPXResultReason.RecognizedSpeech) {
```

**Comment by jibon57** [comment]
@darind thanks. I did like this:
```

            let properties = speechResult.properties;
            //let speechJson = properties.getPropertyById(SPXPropertyId.SpeechServiceResponseJsonResult);

            //console.log(speechJson);
        
  (<any>global).postMessage(JSON.stringify(speechResult.text));

```
& after click on record speak "Hello World". Now I am getting result:
```
CONSOLE LOG: {
"task": "record"
}
file: src/app/item/item-detail.component.ts:93:20:
==== object dump start ====
data: ""Hello World.""
==== object dump end ====
```

This part: `properties.getPropertyById(SPXPropertyId.SpeechServiceResponseJsonResult);`
having problem.

**Comment by darind** [comment]
@jibon57, we have released a fix for this issue. Could you please verify if the Microsoft Cognitive Toolkit is now working properly?

**Comment by jibon57** [comment]
@darind thanks for update. In new version APP isn't starting. I am getting following errors:

```
CONSOLE LOG: Loading inspector modules...
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.speechservice>
CONSOLE LOG: Finished loading inspector modules.
CONSOLE LOG: Loading inspector modules...
(RunningBoardServices) [com.apple.runningboard:connection] Identity resolved as application<org.nativescript.speechservice>
CONSOLE LOG: Finished loading inspector modules.
```
<img width="500" alt="Screen Shot 2020-03-09 at 6 52 48 PM" src="https://user-images.githubusercontent.com/6080277/76214577-3af3c900-6237-11ea-8fb4-9a3b989f068b.png">

**Comment by darind** [comment]
@jibon57, got it, should be working now.

**Comment by jibon57** [comment]
@darind thank you! It's working fine now. 

Another issue also opened in Android Runtime here: https://github.com/NativeScript/android-runtime/issues/1591 . Any suggestion on that?

**Comment by darind** [comment]
@jibon57, that's a completely different issue. I haven't looked into it.
