### ISSUE TITLE
NSRULSessionTask: undefined response

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#40]
This happens with the v8 runtime and not the current runtime.
To reproduce:

* clone https://github.com/farfromrefug/nativescript-https
* `cd src` 
* `npm run demo.ios`
* clilck on the first button. look at the log from here https://github.com/farfromrefug/nativescript-https/blob/master/src/https.ios.ts#L309

**Comment by darind** [comment]
@farfromrefug, we have released a fix for this issue. Could you please try it out?

**Comment by farfromrefug** [comment]
@darind  i can confirm it is fixed.
Thanks
