### ISSUE TITLE
[BUG] - Connectivity.ios.ts problem - cDict.takeUnretainedValue is not a function

### ISSUE THREAD

**Issue by mapo80** [NativeScript/ns-v8ios-runtime#54]
Hi guys,

on my app I use `"tns-core-modules/connectivity"` and using last runtime and last NS core version (6.5.10), I've this error:

`cDict.takeUnretainedValue is not a function`

I've seen that `connectivity.ios.ts` has been modified recently:

https://github.com/NativeScript/NativeScript/commit/635f31f81f7826112142c707aff2a66c2b480b0e#diff-e04e55bc1acfe6688983450e6a16735d

I've this error on app:

 #[Screenshot of app log](https://pasteboard.co/JhJPaUV.png)

**Comment by farfromrefug** [comment]
I can confirm i have the same issue.

**Comment by RibuRoyson** [comment]
same error here also..it crashed...
NativeScript encountered a fatal error: Uncaught TypeError: cfDict.takeUnretainedValue is not a function
at
_getConnectionTypeFromFlags(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:50:0)
at _getConnectionType(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:34:0)
at getConnectionType(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:98:0)
any fix for this??

**Comment by skaledor** [comment]
same error here also..it crashed...

***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught TypeError: cfDict.takeUnretainedValue is not a function
at
_getConnectionTypeFromFlags(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:50:0)
at _getConnectionType(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:34:0)
at getConnectionType(file: node_modules/@nativescript/core/connectivity/connectivity.ios.js:98:0)
at SharedViewModel.viewModel.hayInternet(file: app/shared/view-models/shared-view-model.js:39:0)
at module.exports.push../views/inicio/inicio.js.exports.onLoaded(file: app/views/inicio/inicio.js:44:0)

any solution for this?

**Comment by NathanaelA** [comment]
Can one of you test and see if the 7.0.3 fixes this issue
- `tns platform remove ios` 
- `tns plaform add ios@7.0.3`
Please make sure you run both the remove and add steps

**Comment by darind** [comment]
@NathanaelA, 7.0.3 won’t fix this as it is a different kind of issue. I am currently working on it and will add support for the Unretained type in the runtime which is currently missing.

**Comment by NathanaelA** [comment]
Fixed in #72
