### ISSUE TITLE
iOS app crash after permission request when I use a worker

### ISSUE THREAD

**Issue by jamescodesthings** [NativeScript/ns-v8ios-runtime#63]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: `nativescript@7.0.9-rc.1`
 - Cross-platform modules: `@nativescript/core@7.0.5`
 - Android Runtime: `not tested`
 - iOS Runtime: `@nativescript/ios@7.0.0`
 - Plugin(s): `@nativescript/camera@5.0.0`

**Describe the bug**
Error is:
```
EXC_BAD_ACCESS (code=1, address=0x107f35918)
```

iOS app crash after accepting any permissions, only happens with the worker I've got defined. Could be due to worker termination or mis-handling but any help is appreciated.

Crash Report: [permissionreprod  25-09-2020, 16-53.txt](https://github.com/NativeScript/NativeScript/files/5283886/permissionreprod.25-09-2020.16-53.txt)

**To Reproduce**
See Repo: https://github.com/jamescodesthings/permission-reprod

**Expected behavior**
Nae crash.

**Additional context**
Ripped this out of a bigger, inherited application I'm updating to ns7. This was the smallest reproduction I could work out.

**Comment by NathanaelA** [comment]
Hi, I can confirm the issue.   We will be looking into the issue as time allow.

**Comment by jamescodesthings** [comment]
Cheers 😄

**Comment by darind** [comment]
Can you try refactoring your workers logic so that you have a single long running worker which is always running and executing commands. This is better than spawning and terminating a worker every time you need to perform some operation.

**Comment by jamescodesthings** [comment]
Hey @NathanaelA cheers for looking into the issue, cracking job.

I originally had a single long running worker and found that I'd get the occasional iOS app crash while the app was backgrounded for 30mn or so on an earlier version of the Nativescript 7 releases. I felt the two could be related after seeing the general guidelines docs here: https://docs.nativescript.org/core-concepts/multithreading-model#general-guidelines

In general when working with WebWorkers I was also used to terminating the worker after use to avoid similar restrictions in the browser.

It looks like you've pushed a commit that may address the issue? I can continue to refactor/debug in the mean-time if you'd like any further testing.

Cheers Again! 🎉

**Comment by NathanaelA** [comment]
Based on all my tests we solved that issue in 7.0.3.   
Long running vs short lived - You can use either; but each start of a worker has a performance hit as it has to spin up a entirely new v8 engine effectively, so the best practice is typically to use a single worker that is long lived so that you just send a message to it and it does whatever you need without starting/stopping them.    

If you run into issues with either short or long lived workers, please let us know!   :grinning:

**Comment by jamescodesthings** [comment]
Cheers for clarifying. Appreciate it =]
