### ISSUE TITLE
Crashes when using workers in N7

### ISSUE THREAD

**Issue by CodeWDstudio** [NativeScript/ns-v8ios-runtime#77]
Hi,
We are upgrading an app to N7 that uses the speech recognition plugin for transcribing what someone says. At the same time we record the audio of the speech using a different system. In order to do this successfully on the previous version on Nativescript we put the speech recognition functions in a worker.

Everything works fine until you try and stop the recognition. The app then immediately crashes. We have plugged it in to xCode and the error that seems to consistently come back is 'Cannot create a handle without a HandleScope'. 

Do you know anything about this please? Is N7 known to have issues with workers?

Thanks for the framework, and any help you can provide!

**Comment by darind** [comment]
Any chance you could create a sample app exhibiting the crash?

**Comment by CodeWDstudio** [comment]
Yes sure, please find it attached. I have stripped out everything I can from our app to just demonstrate the issue. I have also removed the platforms and node_modules folder to keep the size down, so it will need a build.
[example-app.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/5466152/example-app.zip)

Thanks for replying so fast!

**Comment by darind** [comment]
@CodeWDstudio, thanks for the sample. We are able to reproduce the issue and will provide a fix in an upcoming release of the runtime.

**Comment by CodeWDstudio** [comment]
Great, thanks, I'll look forward to hearing from you!

**Comment by NathanaelA** [comment]
This should have been fixed in 7.0.5
