### ISSUE TITLE
Switching to v8 causing crash [ui-image]

### ISSUE THREAD

**Issue by keerl** [NativeScript/ns-v8ios-runtime#81]
I am trying to get my app updated to use the iOS v8 runtime, but I am getting some bad crashes with virtually no errors in a few places. 

The error stems from using the [ui-image](https://github.com/nativescript-community/ui-image) plugin. I have reported the issue [there](https://github.com/nativescript-community/ui-image/issues/34), but am adding it here as it seems to be specific to the v8 runtime and not the plugin as it works fine using `tns-ios`.

Here is a simple demo app that shows the problem: [v8-crash-ui-image.zip](https://github.com/NativeScript/ns-v8ios-runtime/files/5537058/v8-crash-ui-image.zip)

When the app loads, it will start loading images and if you start scrolling down the app will violently crash with no error. See attached GIF for demo of crash.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/24727492/98597236-f1f88680-2295-11eb-8fd1-0c2e7330a42d.gif)

I have to go into the crash logs to even see what happened. Here is the error I am getting from there.

![Screen Shot 2020-11-09 at 2 09 59 PM](https://user-images.githubusercontent.com/24727492/98597084-ac3bbe00-2295-11eb-97ca-b478c95d26ff.png)

**Comment by pboulch** [comment]
Same problem here : lib nativescript-community/ui-image v4.0.11 and ns 7.0.10

**Comment by romandragan** [comment]
Same for me on the latest iOS v8 runtime and latest `nativescript-community/ui-image@4.0.13` and latest `SDWebImage` pod `5.9.5`.

Project to reproduce: https://github.com/romandragan/ui-image-crash-radlistview

**Comment by keerl** [comment]
Here is the error from my crash with the demo project attached above.

![Screen Shot 2020-11-17 at 7 28 51 AM](https://user-images.githubusercontent.com/24727492/99403801-195bde80-28a8-11eb-9263-05087652cebe.png)

**Comment by farfromrefug** [comment]
@NathanaelA @NathanWalker let me comment on this as i am the maintainer of the plugin. It really seems to be related with the v8 runtime. We dont see a crash on the classic runtime.
Could you run the example to see the crash through xcode? 
I will try and search through the SdWebImage repo to see if that issue is reported there.

**Comment by darind** [comment]
@keerl, thanks for the detailed report and sample app. A PR that should address this issue is on the way.

**Comment by farfromrefug** [comment]
@darind damn you are fast ;)

**Comment by romandragan** [comment]
Works fine with `@nativescript/ios@7.0.6`.

**Comment by keerl** [comment]
Works now. Thanks @darind !
